[package]
name = "momo"
authors = ["Jasper van den Bogart <jasper.opti@gmail.com>"]
version = "0.1.0"
edition = "2021"

[workspace]
members = ["crates/*"]

[dependencies]
drive = { version = "0.1.0", path = "crates/drive" }
