[package]
name = "lexer"
version = "0.1.0"
edition = "2021"

[dependencies]
query_base = { version = "0.1.0", path = "../query_base" }
source = { version = "0.1.0", path = "../source" }
syntax = { version = "0.1.0", path = "../syntax" }
