name: build rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: build
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOs-latest]
        toolchain: [stable, beta, nightly]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.toolchain }}
      - run: cargo build --workspace --verbose --all-features
      - run: cargo build --workspace --verbose --no-default-features
