name: codecov

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  codecov:
    name: tarpaulin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hecrj/setup-rust-action@v1
      - uses: actions-rs/tarpaulin@v0.1
        with:
          args: --all-features
          # Failing under some percentage seems like a useful trick to keep tabs on codecov; but
          # it is not so useful when most of your code is yet to be written.
          # TODO Replace the line above with the line below once v1.0 goes live.
          # args: --all-features --fail-under 75
