name: fmt

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    name: rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hecrj/setup-rust-action@v1
        with:
          components: rustfmt
      - run: cargo fmt --all
      - name: push changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config user.name 'Jasper van den Bogart'
          git config user.email 'bjogart@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "rustfmt formatting"
          git push
