name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [stable, beta, nightly]
    steps:
      - uses: actions/checkout@v3
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.toolchain }}
      - run: cargo test --workspace --verbose --all-features
      - run: cargo test --workspace --verbose --no-default-features
  miri-test:
    name: miri tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: nightly
          components: miri
      - run: cargo miri test --workspace --verbose --no-default-features
      - run: cargo miri test --workspace --verbose --all-features
